name: CI

on: push

jobs:
  main_job:
    env:
      GIT_BRANCH: 'githubactions'
      GIT_SLUG: 'L30nardoSV/AutoDock-GPU'
    runs-on: ubuntu-latest
    name: Running test via Docker container
    steps:
      - name: Setting up repository
#        uses: L30nardoSV/AutoDock-GPU@githubactions
        uses: actions/checkout@v2
      - name: Dummy
        run: ls -asl ${HOME}
      - name: Dummy
        run: ls -asl ${HOME}/work
      - name: Building the Docker image
        run: docker build --build-arg git_branch=${GIT_BRANCH} --build-arg git_slug=${GIT_SLUG} -t adgpu . --file AutoDock-GPU/Dockerfile
