name: CI

on: push

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: Running test via Docker container
    steps:
      - name: Setting up repository
#        uses: L30nardoSV/AutoDock-GPU@githubactions
        uses: actions/checkout@v2
