on: [push]

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: A preliminary job
    steps:
      - name: Hello world action step
        id: hello
        uses: L30nardoSV/AutoDock-GPU@githubactions
        with:
          git_branch: 'githubactions'
          git_slug: 'L30nardoSV/AutoDock-GPU'
      - name: Get the output time
        run: echo "This is the end"