on: push

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: A preliminary job
    steps:
      - name: Setting up repository
        uses: L30nardoSV/AutoDock-GPU@githubactions
        with:
          build_args: git_branch='githubactions', git_slug='L30nardoSV/AutoDock-GPU'
#      - run: export numwi=16
#      - run: docker run -e numwi adgpu